DomasnaShoppingCart/Models/ErrorViewModel.cs
using System;

namespace DomasnaShoppingCart.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DomasnaShoppingCart/Models/ShoppAdmin/DataModelShopp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DomasnaShoppingCart.Models.ShoppAdmin
{
    public static class DataModelShopp
    {
        public static List<Shopping> Shoppings = new List<Shopping>()
        {
            new Shopping(){Id = 1,Name ="Adidas Boot",Price = 85,Quantity = 10,Expiry = DateTime.Now.AddDays(10),Category="Boots",Brand="Adidas Predator",LogoUrl="https://cdn.pixabay.com/photo/2020/07/22/09/28/adidas-5428548_960_720.jpg"},
              new Shopping(){Id = 2,Name ="Nike Boot",Price = 240,Quantity = 10,Expiry = DateTime.Now.AddDays(10),Category="Boots",Brand="Nike Mercurial",LogoUrl="https://cdn.pixabay.com/photo/2012/02/29/15/44/football-19115_1280.jpg"}
        };
        public static List<Shopping> Cart = new List<Shopping>();
       
    }
}

DomasnaShoppingCart/Models/ShoppAdmin/Shopping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DomasnaShoppingCart.Models.ShoppAdmin
{
    public class Shopping
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Boot Name")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Boot Price")]
        public decimal Price { get; set; }

        [Required]
        [DisplayName("Boot Quantity")]
        public int Quantity { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Expiry Date")]
        public DateTime Expiry { get; set; }

        [Required]
        [DisplayName("Boot Category")]
        public string Category { get; set; }

        [Required]
        [DisplayName("Boot Brand")]
        public string Brand { get; set; }

        [Required]
        [DisplayName("Boot Logo")]
        public string LogoUrl { get; set; }

    }
}

DomasnaShoppingCart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DomasnaShoppingCart.Models;

namespace DomasnaShoppingCart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DomasnaShoppingCart/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DomasnaShoppingCart.Models.ShoppAdmin;

namespace DomasnaShoppingCart.Controllers
{
    public class ShopCartController : Controller
    {
        public IActionResult Index()
        {
            return View(DataModelShopp.Shoppings);
        }

        public IActionResult AddToCart(int id)
        {
            
            var cart = DataModelShopp.Shoppings.FirstOrDefault(x => x.Id == id);
           
            if(cart != null)
            {
                DataModelShopp.Cart.Add(cart);
                cart.Quantity--;
            }
            
            ViewBag.Count = DataModelShopp.Cart.Count();
            return View("Index",DataModelShopp.Shoppings);
        }
        public IActionResult MyCart()
        {
            return View(DataModelShopp.Cart);
        }
        public IActionResult Delete(int id)
        {
            var product = DataModelShopp.Cart.FirstOrDefault(x => x.Id == id);
            DataModelShopp.Cart.Remove(product);
            return RedirectToAction("MyCart");
        }
    }
}

DomasnaShoppingCart/Controllers/ShoppAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DomasnaShoppingCart.Models.ShoppAdmin;
using Microsoft.AspNetCore.Mvc;

namespace DomasnaShoppingCart.Controllers
{
    public class ShoppAdminController : Controller
    {
        public IActionResult Index()
        {
            return View(DataModelShopp.Shoppings);
        }
        public IActionResult Create()
        {
            return View();
;        }
        public IActionResult CreateNewBoot(Shopping shopping)
        {
           DataModelShopp.Shoppings.Add(shopping);
           return RedirectToAction("Index");
            
        }
        public IActionResult Edit(int id)
        {
            var editBoot = DataModelShopp.Shoppings.FirstOrDefault(x => x.Id == id);
            return View(editBoot);
        }
        public IActionResult Update(Shopping shopping)
        {
            var updateBoot = DataModelShopp.Shoppings.FirstOrDefault(x => x.Id == shopping.Id);
            updateBoot.Id = shopping.Id;
            updateBoot.Name = shopping.Name;
            updateBoot.Price = shopping.Price;
            updateBoot.Category = shopping.Category;
            updateBoot.Quantity = shopping.Quantity;
            updateBoot.Expiry = shopping.Expiry;
            updateBoot.Brand = shopping.Brand;
            updateBoot.LogoUrl = shopping.LogoUrl;
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            DataModelShopp.Shoppings.RemoveAll(x => x.Id == id);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var detailsBoot = DataModelShopp.Shoppings.FirstOrDefault(x => x.Id == id);
            return View(detailsBoot);
        }
        public IActionResult Back()
        {
            return RedirectToAction("Index");
        }


    }
}

DomasnaShoppingCart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DomasnaShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DomasnaShoppingCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DomasnaShoppingCart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","ShoppAdmin")" class="nav-link text-dark">ShoppAdmin</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","ShopCart")" class="nav-link text-dark">Shop Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DomasnaShoppingCart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DomasnaShoppingCart/Views/ShopCart/Index.cshtml
@model List<DomasnaShoppingCart.Models.ShoppAdmin.Shopping>
@using DomasnaShoppingCart.Extension

@{
    ViewBag.Title = "Football Boots";
}

<h1>@ViewBag.Title</h1>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category</th>
        <th>Quantity</th>
        <th>Add To Cart</th>
        <th>Expiry Date</th>
        <th>Brand</th>
        <th>Logo</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Category</td>
            <td>@item.Quantity</td>
            <td>
                @if (item.Quantity > 0)
                {
                    <p>Avaible</p>
                    <a href="@Url.Action("AddToCart","ShopCart", new { id=item.Id})" class="nav-link"><i class="fa fa-shopping-cart" style="font-size:36px"></i></a>
                }
                else
                {
                    <p>Unavaible</p>
                }
            </td>
            <td>@item.Expiry</td>
            <td>@item.Brand</td>
            <td>@Html.ImageBanner(item.LogoUrl, "Boot", "100", "100")</td>
        </tr>
    }
</table>
<p>
    @if (DomasnaShoppingCart.Models.ShoppAdmin.DataModelShopp.Cart != null)
    {
        <a href="@Url.Action("MyCart","ShopCart")" class="nav-link">View Your Cart: @ViewBag.Count</a>
    }

</p>

DomasnaShoppingCart/Views/ShopCart/MyCart.cshtml
@model List<DomasnaShoppingCart.Models.ShoppAdmin.Shopping>
@using DomasnaShoppingCart.Extension

@{
    ViewData["Title"] = "MyCart";
}

<h1>MyCart</h1>


<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category</th>
        <th>Quantity</th>
        <th>Expiry Date</th>
        <th>Brand</th>
        <th>Logo</th>
        <th>Delete</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Category</td>
            <td>@item.Quantity</td>
            <td>@item.Expiry</td>
            <td>@item.Brand</td>
            <td>@Html.ImageBanner(item.LogoUrl, "Boot", "100", "100")</td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

DomasnaShoppingCart/Views/ShoppAdmin/Create.cshtml
@model DomasnaShoppingCart.Models.ShoppAdmin.Shopping

@{
    ViewBag.Title = "Create New Boots";
}

<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("CreateNewBoot", "ShoppAdmin", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(x => x.Id)
    @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Id)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Name)
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Name)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Price)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Category)
    @Html.TextBoxFor(x => x.Category, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Category)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Quantity)
    @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Quantity)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Expiry)
    @Html.EditorFor(x => x.Expiry, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Expiry)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.Brand)
    @Html.EditorFor(x => x.Brand, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Brand)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.LogoUrl)
    @Html.EditorFor(x => x.LogoUrl, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.LogoUrl)
</div>

    <input type="submit" value="Create new Boot" class="btn btn-primary" />
}

DomasnaShoppingCart/Views/ShoppAdmin/Details.cshtml
@model DomasnaShoppingCart.Models.ShoppAdmin.Shopping
@using DomasnaShoppingCart.Extension
@{
    ViewData["Title"] = "Details";
}

<h1 class="mb-4">Details for Boot</h1>
<div class="jumbotron text-left col-md-3 border border-dark">
    <p class="font-weight-bold">ID: @Model.Id</p>
    <p class="font-weight-bold">Boot Name: @Model.Name</p>
    <p class="font-weight-bold">Boot Price: @Model.Price</p>
    <p class="font-weight-bold">Boot Category: @Model.Category</p>
    <p class="font-weight-bold">Boot Quantity: @Model.Quantity</p>
    <p class="font-weight-bold">Boot Expiry Date: @Model.Expiry</p>
    <p class="font-weight-bold">Boot Brand: @Model.Brand</p>
    <p class="font-weight-bold">Boot Logo: @Html.ImageBanner(Model.LogoUrl, "Boot", "150", "150")</p>
   
    <a href="@Url.Action("Back","ShoppAdmin")">Back To List</a>
</div>

DomasnaShoppingCart/Views/ShoppAdmin/Edit.cshtml
@model DomasnaShoppingCart.Models.ShoppAdmin.Shopping


<h1>Edit Your Boot</h1>


@using (Html.BeginForm("Update", "ShoppAdmin", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Id)
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Id)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Price)
        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Price)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Category)
        @Html.TextBoxFor(x => x.Category, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Category)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Quantity)
        @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Quantity)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Expiry)
        @Html.EditorFor(x => x.Expiry, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Expiry)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Brand)
        @Html.EditorFor(x => x.Brand, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Brand)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.LogoUrl)
        @Html.EditorFor(x => x.LogoUrl, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.LogoUrl)
    </div>

    <input type="submit" value="Create new Boot" class="btn btn-primary" />
}

DomasnaShoppingCart/Views/ShoppAdmin/Index.cshtml
@model List<DomasnaShoppingCart.Models.ShoppAdmin.Shopping>
@using DomasnaShoppingCart.Extension

@{
    ViewBag.Title = "Boots";
}

<h1>@ViewBag.Title</h1>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category</th>
        <th>Quantity</th>
        <th>Expiry Date</th>
        <th>Brand</th>
        <th>Logo</th>
        <th>Edit/Details/Delete</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Category</td>
            <td>@item.Quantity</td>
            <td>@item.Expiry</td>
            <td>@item.Brand</td>
            <td>@Html.ImageBanner(item.LogoUrl, "Boot", "100", "100")</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Details", "Details", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Create New Boot", "Create", "ShoppAdmin")
</p>